services:
  - type: web
    name: cenariox-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd apps/api && npm install && npx prisma generate && npm run build
    startCommand: cd apps/api && npx prisma migrate deploy && npx prisma db seed || true && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cenariox-db
          property: connectionString

  - type: web
    name: cenariox-web
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://cenariox-api.onrender.com
      - key: NEXTAUTH_URL
        value: https://cenariox-web.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cenariox-db
          property: connectionString

databases:
  - name: cenariox-db
    databaseName: cenariox
    user: cenariox
    plan: free
